server.port: 8081
spring:
    datasource:
        url: jdbc:mysql://*.*.*.*:3306/ji_blog?useUnicode=true&characterEncoding=UTF-8
        username: **
        password: **
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
