server.port: 8081
spring:
    datasource:
        url: jdbc:mysql://39.106.204.141:3306/ji_blog?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 876606
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml